### ISSUE TITLE
#manager admin / user

### ISSUE THREAD

**Issue by NicolasMugnier** [FlorianGG/Projet-4-Creez-un-blog-pour-un-ecrivain#10]
#manager admin / user

refactor method read
-> une méthode read(int $id)
-> une méthode readByEmail($email)
-> une troisieme méthode protected loadByQuery($req)

update db : colonnes email : unique + add index + not null

**Comment by FlorianGG** [comment]
Issues is closed with the commits 6187c12fa4b81847baf125b661e9fed962629395 and 143c5d8c766e75f9bea7541c7331bf2af6f2d2b0
