### ISSUE TITLE
#refactorer les managers

### ISSUE THREAD

**Issue by NicolasMugnier** [FlorianGG/Projet-4-Creez-un-blog-pour-un-ecrivain#11]
#refactorer les managers :
tous les managers doivent hériter de la même classe abstraite
les méthodes create / read / update / delete / count / etc doivent dans la classe parente
les classes filles contienent une attribut $tableName qui contient le nom de la table en bdd

**Comment by FlorianGG** [comment]
# Commit : 
* 8ab4a891a137ac419a06336a4e68864bd83e4e53

## First step : 
* the class ManagerAbstract has been create and all the functions read have been implemented in the mother class ManagerAbstract.

## Next step : 
* Implementation of the functions create

**Comment by FlorianGG** [comment]
Ok the issue has been solve with this last commit a9c1558775bbf7a080af1f801a48bbef43504763
