### ISSUE TITLE
#router

### ISSUE THREAD

**Issue by NicolasMugnier** [FlorianGG/Projet-4-Creez-un-blog-pour-un-ecrivain#13]
#router
attributs $request et $response setter dans le construct avec les objets Request et Response
une seule méthode dispatch
$controller = $this->getRequest()->getParam('controller');
$action = $this->getRequest()->getParam('action');
si controller inexistant: 
	404
sinon:
 	si: action (methode du controller) inexistante:
 		404
 	sinon:
 		return $controller->$action($request, $response);

#index.php

echo $router->dispatch($reqest, $response);

**Comment by FlorianGG** [comment]
Issue has been solve with the commit c85f26f3e65bacbbe957479fc3e9f0c243444358
