### ISSUE TITLE
#chainer les appels

### ISSUE THREAD

**Issue by NicolasMugnier** [FlorianGG/Projet-4-Creez-un-blog-pour-un-ecrivain#14]
#chainer les appels
dans tous les objets, dans toutes les métgodes ne retournant pas qqchose, retourner l'objet courrant ($this)
ex : $article->setTitle($title)->setContent($content)->setAuthor($author)->save();

**Comment by FlorianGG** [comment]
# Chain the calls of methods

## Commit : 
* 1a32166c21f9e91acabbe6a05b9b80d34afe1b0a
## Comments : 
* Implementation only in the methods which return nothing so only for the setters
* But I cannot use them because I use hydrate function to set the attributes
