### ISSUE TITLE
#namespace

### ISSUE THREAD

**Issue by NicolasMugnier** [FlorianGG/Projet-4-Creez-un-blog-pour-un-ecrivain#15]
Commencer à regarder comment utiliser les namespaces et essayer de les utiliser sur le projet.

**Comment by FlorianGG** [comment]
# Namespace

## Commit :
* Begin with the commit fa9fde9fb4fca3750c3a0cb5b0bf5cea41765e01
* Finish with the commit 8fb33b3d620905f137b18883b1640a8e79cf1ca0

## Comment :
* Each page or classe is able to run correctly with the implementation of namespaces
* Modification of the Autoloader :
  * Creation of new class Autoloader with two static functions : register and autoload
  * The function autoload has been updated
* Problem with the creation of new dynamic classes :
  * I have to use a var with the beginning of the namespaces in the functions readAll and loadByQuery in the ManagerAbstract
