### ISSUE TITLE
Les méthodes de type action des controllers ne doivent pas prendre de paramètres

### ISSUE THREAD

**Issue by NicolasMugnier** [FlorianGG/Projet-4-Creez-un-blog-pour-un-ecrivain#16]

**Comment by FlorianGG** [comment]
# Not using parameters in the action methods of controllers
## Commit : 
* e065f8b972051dd2c1fc9b8d19bae54ae73279a4
## Comments : 
* Using of the object request and response setter in the construct
* Now the methods get back the parameter id with $this->request->getParam('Id');
