### ISSUE TITLE
Refactorer les controllers de façon a ce que les méthodes n'aient qu'un return

### ISSUE THREAD

**Issue by NicolasMugnier** [FlorianGG/Projet-4-Creez-un-blog-pour-un-ecrivain#17]

**Comment by FlorianGG** [comment]
# Refactore the methods of the controller
## Commit : 
* b7308eeafa3c7f4ad8bf100dbe8405a3107bdfb6
## Comments : 
* Using of only one return my function
* Each condition set the variable $html and at the end of the method, we return it.
