### ISSUE TITLE
Supprimer tous les attributs requestGet & requestPost

### ISSUE THREAD

**Issue by NicolasMugnier** [FlorianGG/Projet-4-Creez-un-blog-pour-un-ecrivain#18]
les accès aux params de l'object Request se font uniquement via $this->getRequest()->getParam($param);

**Comment by FlorianGG** [comment]
# Delete all the requestGet and requestPost attributes
## Commit : 
* e065f8b972051dd2c1fc9b8d19bae54ae73279a4
## Comments : 
* Using of the object request and response setter in the construct
* ex : $this->request = request and using function $this->request->getParam()
* Not parameter in the function dispatch. We have to use directly $this->request
