### ISSUE TITLE
Encapsuler les managers dans les modèles

### ISSUE THREAD

**Issue by NicolasMugnier** [FlorianGG/Projet-4-Creez-un-blog-pour-un-ecrivain#19]

**Comment by FlorianGG** [comment]
# Encapsulate the managers in the models
## Commit : 
* e69695dc835ded7ae4e81350a456449b2c636480
## Comments : 
* The parameter call in the construct of each model can now be null
* There are 3 methods in the modelAbstract to drive the managers(delete, read (ie load), readAll(io getCollection))
* Update of the method loadByEmail in Admin & User from static to public
