### ISSUE TITLE
create method redirect in Response object

### ISSUE THREAD

**Issue by NicolasMugnier** [FlorianGG/Projet-4-Creez-un-blog-pour-un-ecrivain#20]
add method Response::redirect($code, $message) 
use this method in Router class for dispatch 404 error.

**Comment by FlorianGG** [comment]
# Creation of method which redirects in Response object
## Commit : 
* 104664eb0081db1ff3a06a518660f262e0aa6a16
## Comments : 
* Adding of method in Response redirect(code, message)
* This method is used in Router class for dispatch 404 error
