### ISSUE TITLE
hash password in database

### ISSUE THREAD

**Issue by NicolasMugnier** [FlorianGG/Projet-4-Creez-un-blog-pour-un-ecrivain#21]

**Comment by FlorianGG** [comment]
# Hash password in database
## Commit : 
* 51cb3a93480a3090b5c3789983d3d4c4c52b76a7
## Comments : 
* Column pseudo is now unique in user and admin tables of the DB
* Hashing done with sha1 method + prefixe
* Prefix defines as CONST in the ModelPersonAbstract Class
* Add function create in ManagerPersonAbstract which hashes the password before to call create() of his parent
* login() in AdminAuth class, hashes the password and check if it is equal to the password of the DB
* if ok return true else return error 403 forbidden
