### ISSUE TITLE
Refactor views

### ISSUE THREAD

**Issue by NicolasMugnier** [FlorianGG/Projet-4-Creez-un-blog-pour-un-ecrivain#22]
no namespace,
no use,
just variables + echo + foreach, if etc

**Comment by FlorianGG** [comment]
# Update view files 
## Commit : 
* ea241cf85adfc515ded133ca439155be17f87e22
## Comments : 
* Deleting namespaces, use and using just variables, echo foreach and if
* New structure of folders with an admin and front parts
