### ISSUE TITLE
Set session id

### ISSUE THREAD

**Issue by NicolasMugnier** [FlorianGG/Projet-4-Creez-un-blog-pour-un-ecrivain#23]
Set session Id in Auth class + add session Id in url

**Comment by FlorianGG** [comment]
# Set session id
## Commit : 
* 674f812377739e992e723f1d2bad7df5616504de
## Comments : 
* Deleting of SESSION['pseudo'] and SESSION['pass'], using of SESSION['id']
* The variable SESSION is set in the class Auth with the id

**Comment by FlorianGG** [comment]
# Set session id
## Commit : 
* 0643dd5ceb0b52080f5b3739dceb252152bfe2fa
## Comments : 
* add !is_null(SESSION['id] in 'if' condition of logged method in Auth class
