### ISSUE TITLE
Create admin controllers

### ISSUE THREAD

**Issue by NicolasMugnier** [FlorianGG/Projet-4-Creez-un-blog-pour-un-ecrivain#24]
create directory Controller/Admin
create controllers : 
home (inexAction display hello) 
article (indexAction : list with edit & delete buttons, editAction : display edit form, deleteAction) 
user (logout)

all admin controllers must check that user is logged, if not redirect to authentication form.

**Comment by FlorianGG** [comment]
# Create admin controllers
## Commit : 
* 674f812377739e992e723f1d2bad7df5616504de
## Comments : 
* Finalisation of directory controller/admin with 3 controllers home, article and auth
* Each controller check in his construct if the user is logged else redirection to authentification form
