### ISSUE TITLE
Create specific layout for admin

### ISSUE THREAD

**Issue by NicolasMugnier** [FlorianGG/Projet-4-Creez-un-blog-pour-un-ecrivain#25]
admin controllers must use specific layout

**Comment by FlorianGG** [comment]
# Create specific layout for admin
## Commit : 
* 674f812377739e992e723f1d2bad7df5616504de
## Comments : 
* There is a specific layout for the admin controllers and also specific contents
* Each specific content is placed in the corresponding  controller folder
