### ISSUE TITLE
Add redirectUrl method in Response object

### ISSUE THREAD

**Issue by NicolasMugnier** [FlorianGG/Projet-4-Creez-un-blog-pour-un-ecrivain#26]
create method Response::redirectUrl($url, $code = '200');

**Comment by FlorianGG** [comment]
# Add redirectUrl method in Response object
## Commit : 
* 674f812377739e992e723f1d2bad7df5616504de
## Comments : 
* Creation of method in Response class, redirectUrl(url) which sent back the page in parameter
* Problem with the parameter code because I don't know how use it
