### ISSUE TITLE
Implement request object

### ISSUE THREAD

**Issue by NicolasMugnier** [FlorianGG/Projet-4-Creez-un-blog-pour-un-ecrivain#7]
implémenter la classe Request (model/http)
 - getParam($param)
 - getParams()
 - getPost()
 --> les méthodes retournent les valeurs nettoyées
 --> si valeur inexistante la méthode retourne null

Remplacer tous les appels à $_GET par Request::getParam dans index.php 
Passer l'objet Request au controller lors de l'instanciation
Utiliser un attribut protected $request dans tous les controllers
Remplacer tous les appels à $_GET par Request::getParam dans les controllers

**Comment by FlorianGG** [comment]
Issue closed with the commit 8c7003582acd32e8eb744d17986df208ca8b64b2
