### ISSUE TITLE
Implement Router class

### ISSUE THREAD

**Issue by NicolasMugnier** [FlorianGG/Projet-4-Creez-un-blog-pour-un-ecrivain#8]
implémenter la classe model/Router.php
 - dispatch()
 - on lui passe l'objet request en param lors de l'instanciation
 - utilisation d'un attribut de classe protected $request

 --> objectif de ce objet : analyser l'url à l'aide de l'objet Request et retrouver le controller et la méthode à utiliser.

 -> si le controller et la méthode existe -> retourne la réponse du controller
 -> si le controller n'existe pas ou que le méthode n'existe pas -> envoie d'une erreur 404 au nivigateur (header)

**Comment by FlorianGG** [comment]
Ok it's done with commit 6c94ef273611d3364c7c72677759fdb68bb55e61
