### ISSUE TITLE
Implement Response class

### ISSUE THREAD

**Issue by NicolasMugnier** [FlorianGG/Projet-4-Creez-un-blog-pour-un-ecrivain#9]
implémenter la classe Response (model/http)
 - setBody($html)
 - __toString()
 --> utilisation d'un attribut pour stocker le contenu setter via la méthode setBody($html)

 -> utilisation de cet objet dans les controller.
 -> le retour d'un controller doit resembler à $this->response->setBody($html);

**Comment by FlorianGG** [comment]
Implementation done withe the commit a512d56f914275e2734eacd46c362d82228bf006
